version: "3.9"
services:
  mariadb:
    image: mariadb:10.3.36
    platform: linux/x86_64
    container_name: gilanotification-mariadb
    env_file:
      - ./backend/.env
    ports:
      - "33062:3306"
  redis:
    image: redis:alpine
    container_name: gilanotification-redis
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
    restart: unless-stopped
    ports:
      - "63792:6379"
  php-apache:
    build:
      context: backend/docker/php-apache
    container_name: gilanotification-php-apache
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8012:80"
    depends_on:
      - mariadb
      - redis
    links:
      - mariadb
      - redis
  phpmyadmin:
    image: phpmyadmin
    container_name: gilanotification-phpmyadmin
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "1337:80"
  nextjs:
    build: .
    container_name: gilanotification-nextjs
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
